name: my application
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.0-alpha.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0-alpha.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
        
    - name: CD
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        PORT: ${{ secrets.PORT }}
        script: |
          cd /home/cicd-flask
          git pull
          fuser -k 5000/tcp
          source venv/bin/activate
          python app.py
