name: my application
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2   
        
    - name: CD
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        PORT: ${{ secrets.PORT }}
        script: |
          cd /home/cicd-flask
          fuser -k -n tcp 5000
          source venv/bin/activate
          python app.py
